### PR TITLE
chore: optimize publish workflow

### LINKED ISSUE #417: A smoother release process
- more automated scripts to prepare release
  - auto checkout needed branch
  - fixed release message
- use the GitHub release message instead of custom message
  - using the GitHub release generated template as release message

### PR DESCRIPTION
**Pull request by PainterPuppets**
# Description

Automatically create a new branch & commit after running `yarn versionup`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Website
- [ ] Example
- [x] Other

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by homura** [comment]
hi @PainterPuppets, can you help to test if this action can

- [ ] release automatically determines which version it is based on(by lerna.json)
- [ ] the release message is something like [this](https://github.com/ckb-js/lumos/releases/tag/v0.19.0-alpha.3)

if so, can you help provide a release success story?

**Comment by PainterPuppets** [comment]
> hi @PainterPuppets, can you help to test if this action can
> 
> * [ ]  release automatically determines which version it is based on(by lerna.json)
> * [ ]  the release message is something like [this](https://github.com/ckb-js/lumos/releases/tag/v0.19.0-alpha.3)
> 
> if so, can you help provide a release success story?

Using the changelog generated by Lerna as the release body, I don't know if it will meet the requirements

image

**Review by homura — APPROVED** [review]

**Comment by PainterPuppets** [comment]
@homura Wait... There is some code still not uploaded, should I open a other pull request to fix it?

**Comment by homura** [comment]
> @homura Wait... There is some code still not uploaded, should I open a other pull request to fix it?

please mark an unfinished PR to be a draft PR next time

**Pull request merged**
